// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuna;

namespace Tuna.Migrations
{
    [DbContext(typeof(TunaContext))]
    partial class TunaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tuna.Models.AverageTrashDistribution", b =>
                {
                    b.Property<int>("District");

                    b.Property<float>("FoodWaste");

                    b.Property<float>("PlasticWaste");

                    b.Property<float>("ResidualWaste");

                    b.HasKey("District");

                    b.ToTable("AverageTrashDistribution");
                });

            modelBuilder.Entity("Tuna.Models.Household", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("District");

                    b.Property<int>("NumberOfAdults");

                    b.Property<int>("NumberOfChildren");

                    b.Property<string>("OwnerId");

                    b.Property<int>("Points");

                    b.HasKey("HouseholdId");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("Tuna.Models.WasteCollection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CollectionDate");

                    b.Property<int>("FoodWaste");

                    b.Property<Guid>("HouseholdId");

                    b.Property<int>("PlasticWaste");

                    b.Property<int>("ResidualWaste");

                    b.HasKey("CollectionId");

                    b.ToTable("WasteCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
